// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDtfEI2jm0kRgnVxF-XUgGxe980GsrmzY',
    appId: '1:334675337000:web:9078d093228818539c7a1d',
    messagingSenderId: '334675337000',
    projectId: 'flutter-firebaseui',
    authDomain: 'flutter-firebaseui.firebaseapp.com',
    storageBucket: 'flutter-firebaseui.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJt-NzFqbaKJVypBRVuCXRo7dMFxc3vnM',
    appId: '1:334675337000:android:518519961ffe4d9e9c7a1d',
    messagingSenderId: '334675337000',
    projectId: 'flutter-firebaseui',
    storageBucket: 'flutter-firebaseui.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVFZgF2okiFOfTb6COtb05kb-863pVgzM',
    appId: '1:334675337000:ios:73053995d9949d8d9c7a1d',
    messagingSenderId: '334675337000',
    projectId: 'flutter-firebaseui',
    storageBucket: 'flutter-firebaseui.appspot.com',
    iosClientId: '334675337000-vnv0f5f7uo1j540noglmighcsp5ovdip.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVFZgF2okiFOfTb6COtb05kb-863pVgzM',
    appId: '1:334675337000:ios:73053995d9949d8d9c7a1d',
    messagingSenderId: '334675337000',
    projectId: 'flutter-firebaseui',
    storageBucket: 'flutter-firebaseui.appspot.com',
    iosClientId: '334675337000-vnv0f5f7uo1j540noglmighcsp5ovdip.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseui',
  );
}
